plugins {
    id 'com.gradle.develocity' version '3.19.2'
}

develocity {
    buildScan {
        termsOfUseUrl = 'https://gradle.com/terms-of-service'
        termsOfUseAgree = 'yes'
    }
}

rootProject.name = 'mycolection_with_sdd'

include 'backend'
include 'bff'

// Frontend foi removido do Gradle.
// Use npm diretamente na pasta frontend/
